fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    ruby: "git://github.com/puppetlabs/puppetlabs-ruby.git"
    datacat: "git://github.com/richardc/puppet-datacat"
  symlinks:
    datadog_agent: "#{source_dir}"
